import SwiftUI

/// Settings pane for the Surf Escape feature: which calendar to block time on,
/// and how fake meeting titles are generated. Presented as a popover from the
/// gear button in the menubar header.
struct SettingsView: View {
    let calendarService: CalendarService
    /// Generator used by "Test" — honors the currently selected backend.
    let titleGenerator: MeetingTitleGenerator

    private let settings = SettingsStore.shared

    @State private var calendars: [CalendarInfo] = []
    @State private var calendarAccessGranted = true
    @State private var testTitle: String?
    @State private var isTesting = false

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Label("Settings", systemImage: "gearshape")
                    .font(.system(size: 14, weight: .semibold))
                Spacer()
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            Divider()

            Form {
                Section("Surf Escape") {
                    Picker("Block time on", selection: calendarBinding) {
                        Text("Default calendar").tag(String?.none)
                        ForEach(calendars) { cal in
                            Text(cal.title).tag(String?.some(cal.id))
                        }
                    }
                    if !calendarAccessGranted {
                        Text("Calendar access not granted. Enable it in System Settings → Privacy & Security → Calendars.")
                            .font(.system(size: 11))
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }

                Section("Meeting Titles") {
                    Picker("Generated by", selection: backendBinding) {
                        ForEach(SettingsStore.TitleBackend.allCases) { backend in
                            Text(backend.displayName).tag(backend)
                        }
                    }
                    HStack(spacing: 10) {
                        Button(action: runTest) {
                            if isTesting {
                                ProgressView().controlSize(.small)
                            } else {
                                Text("Test")
                            }
                        }
                        .disabled(isTesting)

                        if let testTitle {
                            Text("\u{201C}\(testTitle)\u{201D}")
                                .font(.system(size: 12))
                                .foregroundStyle(.secondary)
                                .lineLimit(1)
                                .truncationMode(.tail)
                        }
                        Spacer()
                    }
                }
            }
            .formStyle(.grouped)
        }
        .frame(width: 360, height: 330)
        .task { await loadCalendars() }
    }

    /// Reads/writes the chosen calendar straight through to `SettingsStore`,
    /// keeping a single source of truth (the store is not observable).
    private var calendarBinding: Binding<String?> {
        Binding(get: { settings.defaultCalendarID },
                set: { settings.defaultCalendarID = $0 })
    }

    private var backendBinding: Binding<SettingsStore.TitleBackend> {
        Binding(get: { settings.titleBackend },
                set: {
                    settings.titleBackend = $0
                    testTitle = nil   // clear stale test output when backend changes
                })
    }

    private func loadCalendars() async {
        calendarAccessGranted = await calendarService.requestAccess()
        calendars = calendarService.availableCalendars()
    }

    private func runTest() {
        isTesting = true
        testTitle = nil
        Task {
            let title = await titleGenerator.generateTitle()
            testTitle = title
            isTesting = false
        }
    }
}
